# Generated by Django 2.2.4 on 2019-08-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cal',
            name='category1',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='cal',
            name='category2',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
