# Generated by Django 2.2.4 on 2019-08-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0007_auto_20190809_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cal',
            name='category1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cal',
            name='category2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cal',
            name='cer',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cal',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
